main:
  dev:
    url: http://dev.site:3000
saveur_shop:
  token: saveurshop
  annual_fee: 200
  dev:
    url: http://saveurshop.dev.site:3000
    categories:
      approval
    pages:
      index: /
      login: /login