capybara_driver: selenium
user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/43.0.2357.81 Chrome/43.0.2357.81 Safari/537.36
screenshot_path: ./tmp/
credentials_file: ./credentials.yml
staging_host: stagingnowshop.com
paypal_callbacks:
  agreement: http://dev.site:3000/api/pay_pal/billing_agreement/success
  permissions: http://dev.site:3000/api/pay_pal/permissions/callback